# creating a headless service
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  namespace: headless-svc
spec:
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8081
  selector:
    app: kube