apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  # Can be mounted by a single client for reading and writing.
  - ReadWriteOnce
  # Or, can be mounted by multiple clients for reading only.
  - ReadOnlyMany
  # After the claim is released, the PV should be retained (not erased or deleted).
  # Two other reclaim policies are: Recycle and Delete.
  persistentVolumeReclaimPolicy: Retain
  # Backed by GCE persistent disk.
  gcePersistentDisk:
    pdName: mongodb
    fsType: ext4
