apiVersion: v1
kind: persistentVolumeClaim
metadata:
  # This name can be used as pod's volume.
  name: mongodb-pvc
spec:
  resources:
    requests:
      storage: 1Gi
    accessModes:
    # Will support single client performing both read and writes.
    - ReadWriteOnce
    storageClassName: ""