apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kube
  template:
    metadata:
      name: kube
      labels:
        app: kube
    spec:
      containers:
      - name: go-api
        image: goku321/go-handler:v1.0