apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ditch
spec:
  rules:
    - host: ditch.example.com
      http:
        paths:
        - path: /
          backend:
            serviceName: svc-discovery
            servicePort: 8080