apiVersion: batch/v1
kind: Job
metadata:
  name: redis-list-writer
spec:
  template:
    spec:
      containers:
      - name: redis-list-writer
        image: goku321/redis-cluster-list:v1.1
        imagePullPolicy: IfNotPresent
        command: ["./main"]
        env:
        - name: REDIS_ADDRESS
          value: "10.3.255.10:6379"
        - name: REDIS_PASSWORD
          value: 26uR4NMc7k
        - name: LIST_NAME
          value: my-list
        - name: NO_LIST_ITEMS_TO_WRITE
          value: "200"
        args: ["write"]
      restartPolicy: Never
  backoffLimit: 4